spring.application.name=marketplace
logging.pattern.console=%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %cyan(%logger{36}) - %yellow(%msg%n)

spring.profiles.active=${CURR_ENV:dev}
application.security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:dev-secret-key-change-me}
application.security.jwt.expiration=${SECURITY_JWT_SECRET_KEY_EXPIRATION:3600000}

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

app.cors.allowed-origins=${FRONTEND_URL_PROD:http://localhost:5173}