# Development profile
spring.datasource.url=${DEV_DATABASE_URL}
spring.datasource.username=${DEV_DATABASE_USERNAME}
spring.datasource.password=${DEV_DATABASE_PASSWORD}

spring.h2.console.enabled=true

# Ensure SQL scripts run on startup
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.encoding=UTF-8