# Production profile (prod) - read DB settings from environment variables
spring.datasource.url=${PROD_DATABASE_URL}
spring.datasource.username=${PROD_DATABASE_USERNAME}
spring.datasource.password=${PROD_DATABASE_PASSWORD}

# Example for PostgreSQL driver; change if using a different DB
spring.datasource.driver-class-name=org.postgresql.Driver

# Disable Spring's automatic SQL initialization in production
spring.sql.init.mode=never
#spring.sql.init.mode=always
spring.h2.console.enabled=false
spring.sql.init.platform=postgresql
spring.sql.init.schema-locations=classpath:schema-postgresql.sql

# LOGGING
logging.file.name=${LOGGING_PATH}
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE